#!/opt/local/bin/bash
# Add below to, or source it from, .bashrc or .bash_profile.
# Change below with correct path to myemacs script.
# "myemacs" alias below will be used for convenience. $PATH can equally be modified to
#+ point to the myemacs script.
#
# If you don't want to make emacsclient as the default editor, you don't need the first 2
#+ lines. Just alias myemacs to the path of the myemacs script file. 

# Set Emacs as default editor
export EDITOR=$HOME/Documents/github/myemacsclient/myemacs
export VISUAL="$EDITOR"
export SUDO_EDITOR="/Applications/MacPorts/Emacs.app/Contents/MacOS/bin/emacsclient --alternate-editor='' -c"
alias myemacs="$EDITOR"
alias sudoedit="sudo -e"
